// Re-export everything from the new error structure

export type {
  AllErrorCodes,
  ColorErrorData,
  ConfigErrorData,
  ErrorOptions,
  FunctionsErrorData,
  InterpreterErrorData,
  LexerErrorData,
  OperationsErrorData,
  ParserErrorData,
  ProcessorErrorData,
  SerializedError,
  SymbolsErrorData,
  UnitErrorData,
} from "./errors/index";
export {
  ColorErrorCode,
  ConfigErrorCode,
  FunctionsErrorCode,
  getMessage,
  InterpreterError,
  InterpreterErrorCode,
  isInterpreterError,
  isLanguageError,
  isLexerError,
  isParserError,
  isProcessorError,
  LanguageError,
  LexerError,
  LexerErrorCode,
  OperationsErrorCode,
  ParserError,
  ParserErrorCode,
  ProcessorError,
  ProcessorErrorCode,
  SymbolsErrorCode,
  serializeError,
  UnitErrorCode,
} from "./errors/index";
