export enum UnitManagerError {
  INVALID_UNIT_TYPE = "INVALID_UNIT_TYPE",
  MISSING_TO_ABSOLUTE = "MISSING_TO_ABSOLUTE",
  MISSING_SPEC = "MISSING_SPEC",
  NO_CONVERSION_PATH = "NO_CONVERSION_PATH",
  MULTIPLE_RELATIVE_UNITS = "MULTIPLE_RELATIVE_UNITS",
  CONVERSION_EXECUTION_FAILED = "CONVERSION_EXECUTION_FAILED",
}

export type UnitManagerErrorType = UnitManagerError;
