/**
 * Error codes for preset validators.
 * Used to identify specific validation failures.
 */
export enum ValidatorCode {
  // Type errors
  EXPECTED_NUMBER = "EXPECTED_NUMBER",
  EXPECTED_STRING = "EXPECTED_STRING",
  EXPECTED_BOOLEAN = "EXPECTED_BOOLEAN",
  EXPECTED_COLOR = "EXPECTED_COLOR",
  EXPECTED_NUMBER_WITH_UNIT = "EXPECTED_NUMBER_WITH_UNIT",
  EXPECTED_LIST = "EXPECTED_LIST",
  EXPECTED_STRUCTURED = "EXPECTED_STRUCTURED",

  // Numeric constraint errors
  VALUE_TOO_SMALL = "VALUE_TOO_SMALL",
  VALUE_TOO_LARGE = "VALUE_TOO_LARGE",

  // String constraint errors
  VALUE_NOT_IN_ENUM = "VALUE_NOT_IN_ENUM",

  // Unit constraint errors
  UNIT_NOT_ALLOWED = "UNIT_NOT_ALLOWED",
  UNIT_DISALLOWED = "UNIT_DISALLOWED",

  // List constraint errors
  LIST_LENGTH_INVALID = "LIST_LENGTH_INVALID",

  // Union/or errors
  NO_VALIDATOR_MATCHED = "NO_VALIDATOR_MATCHED",

  // Struct errors
  REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING",
  FIELD_MISSING = "FIELD_MISSING",
  UNKNOWN_FIELD = "UNKNOWN_FIELD",
}
