name: Test/Publish Workflow

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm i --dev

    - name: Run code quality checks
      run: npm run check

    - name: Run tests
      run: npm test

    - name: Test CLI functionality
      run: |
        npm run cli:interactive -- --help || true
        npm run cli -- parse_tokenset --help
        npm run cli -- permutate_tokenset --help

  build:
    name: Build Library
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build library
      run: npm run build:lib
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          !dist/**/*.map
        retention-days: 7

  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Install dependencies
      run: npm ci

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Update version in package.json
      run: |
        jq '.version = "${{ steps.get_version.outputs.VERSION }}"' package.json > package.tmp.json
        mv package.tmp.json package.json

    - name: Build library
      run: npm run build:lib

    - name: Publish to GitHub Packages
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Check for outdated dependencies
      run: npm outdated || true
