name: Compliance Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout compliance suite
        uses: actions/checkout@v4
        with:
          repository: tokens-studio/tokenscript-compliance-suite
          path: tokenscript-compliance-suite
          ref: 38ee5f15598a0f0de413ae446c2fc2e3645eac87
          token: ${{ secrets.GH_PAT_STANDARD_COMPLIANCE }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build CLI
        run: npm run build

      - name: Run compliance suite (source)
        run: npm run cli -- evaluate_standard_compliance --test-dir ./tokenscript-compliance-suite/tests/ --output compliance-report.json

      - name: Run compliance suite (built) - verification
        run: ./dist/cli.js evaluate_standard_compliance --test-dir ./tokenscript-compliance-suite/tests/ --output compliance-report-built.json

      - name: Verify compliance consistency
        run: |
          echo "Comparing source and built compliance results..."
          source_passed=$(jq -r '.passed' compliance-report.json)
          built_passed=$(jq -r '.passed' compliance-report-built.json)
          if [ "$source_passed" = "$built_passed" ]; then
            echo "✅ Source and built CLI produce consistent results: $source_passed passed"
          else
            echo "❌ Inconsistent results: source=$source_passed, built=$built_passed"
            exit 1
          fi

      - name: Report compliance results
        run: node .github/scripts/report-compliance.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

